import type { Appointment } from "@/contexts/shared-data-context"

// Mock appointments data
export const mockAppointments: Appointment[] = [
  {
    id: "A001",
    patientId: "P001",
    patientName: "John Doe",
    doctorId: "2",
    doctorName: "Dr. Sarah Johnson",
    date: "2023-10-16",
    time: "09:30",
    duration: 30,
    type: "Checkup",
    status: "Scheduled",
    notes: "Regular dental checkup",
    room: "Room 1",
    createdBy: "4", // Receptionist
    createdAt: "2023-10-10T14:30:00Z",
  },
  {
    id: "A002",
    patientId: "P002",
    patientName: "Jane Smith",
    doctorId: "2",
    doctorName: "Dr. Sarah Johnson",
    date: "2023-10-16",
    time: "10:15",
    duration: 45,
    type: "Follow-up",
    status: "Scheduled",
    notes: "Follow-up after filling procedure",
    room: "Room 1",
    createdBy: "4", // Receptionist
    createdAt: "2023-10-09T11:20:00Z",
  },
  {
    id: "A003",
    patientId: "P003",
    patientName: "Robert Johnson",
    doctorId: "7",
    doctorName: "Dr. James Wilson",
    date: "2023-10-16",
    time: "11:00",
    duration: 60,
    type: "Consultation",
    status: "Checked In",
    notes: "Initial consultation for dental implants",
    room: "Room 2",
    createdBy: "4", // Receptionist
    createdAt: "2023-10-08T09:45:00Z",
  },
  {
    id: "A004",
    patientId: "P004",
    patientName: "Emily Davis",
    doctorId: "2",
    doctorName: "Dr. Sarah Johnson",
    date: "2023-10-16",
    time: "13:30",
    duration: 45,
    type: "Procedure",
    status: "Scheduled",
    notes: "Dental filling for cavity on lower right molar",
    room: "Room 1",
    createdBy: "4", // Receptionist
    createdAt: "2023-10-07T16:15:00Z",
  },
  {
    id: "A005",
    patientId: "P005",
    patientName: "Michael Brown",
    doctorId: "7",
    doctorName: "Dr. James Wilson",
    date: "2023-10-16",
    time: "14:45",
    duration: 30,
    type: "Checkup",
    status: "Scheduled",
    notes: "Regular dental checkup and cleaning",
    room: "Room 3",
    createdBy: "4", // Receptionist
    createdAt: "2023-10-06T10:30:00Z",
  },
]
