import type { Patient } from "@/contexts/shared-data-context"

// Mock patients data
export const mockPatients: Patient[] = [
  {
    id: "P001",
    name: "John Doe",
    email: "john.doe@example.com",
    phone: "+233 123456789",
    dateOfBirth: "1978-05-15",
    gender: "Male",
    address: "123 Main St, Accra, Ghana",
    insuranceProvider: "National Health Insurance",
    insuranceNumber: "INS123456",
    medicalHistory: "Hypertension, Diabetes",
    allergies: ["Penicillin", "Latex"],
    assignedDoctor: "Dr. Sarah Johnson",
    assignedNurse: "Nurse Emily",
    lastVisit: "2023-10-15",
    status: "Active",
    registeredDate: "2022-03-10",
  },
  {
    id: "P002",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    phone: "+233 987654321",
    dateOfBirth: "1985-08-22",
    gender: "Female",
    address: "456 Oak St, Accra, Ghana",
    insuranceProvider: "MetLife Dental",
    insuranceNumber: "INS789012",
    medicalHistory: "None",
    allergies: [],
    assignedDoctor: "Dr. Michael Lee",
    assignedNurse: null,
    lastVisit: "2023-10-10",
    status: "Active",
    registeredDate: "2022-05-18",
  },
  {
    id: "P003",
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "+233 456789123",
    dateOfBirth: "1965-12-03",
    gender: "Male",
    address: "789 Pine St, Accra, Ghana",
    insuranceProvider: "National Health Insurance",
    insuranceNumber: "INS345678",
    medicalHistory: "Heart condition, Arthritis",
    allergies: ["Aspirin", "Sulfa drugs"],
    assignedDoctor: "Dr. Sarah Johnson",
    assignedNurse: "Nurse Emily",
    lastVisit: "2023-09-30",
    status: "Active",
    registeredDate: "2021-11-05",
  },
  {
    id: "P004",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    phone: "+233 234567890",
    dateOfBirth: "1992-04-17",
    gender: "Female",
    address: "101 Elm St, Accra, Ghana",
    insuranceProvider: "None",
    insuranceNumber: "",
    medicalHistory: "Asthma",
    allergies: ["Pollen", "Dust mites"],
    assignedDoctor: "Dr. Michael Lee",
    assignedNurse: null,
    lastVisit: "2023-09-25",
    status: "Inactive",
    registeredDate: "2022-08-12",
  },
  {
    id: "P005",
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "+233 876543210",
    dateOfBirth: "1970-09-28",
    gender: "Male",
    address: "202 Cedar St, Accra, Ghana",
    insuranceProvider: "MetLife Dental",
    insuranceNumber: "INS901234",
    medicalHistory: "High cholesterol",
    allergies: [],
    assignedDoctor: "Dr. Sarah Johnson",
    assignedNurse: "Nurse Emily",
    lastVisit: "2023-09-20",
    status: "Active",
    registeredDate: "2022-01-20",
  },
  {
    id: "P006",
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    phone: "+233 345678901",
    dateOfBirth: "1988-11-12",
    gender: "Female",
    address: "303 Birch St, Accra, Ghana",
    insuranceProvider: "National Health Insurance",
    insuranceNumber: "INS567890",
    medicalHistory: "None",
    allergies: ["Shellfish"],
    assignedDoctor: "Dr. Michael Lee",
    assignedNurse: "Nurse Emily",
    lastVisit: "2023-09-15",
    status: "Active",
    registeredDate: "2022-06-30",
  },
]
